/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

/**
 *
 * @author Rakotomalala Cédric
 */
public class FrmAdminStatsMoniteurEtVehicule extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdminStatsMoniteurEtVehicule
     */
    public FrmAdminStatsMoniteurEtVehicule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnMoniteurSollicite = new javax.swing.JTable();
        lblUnMoniteurSollicité = new javax.swing.JLabel();
        lblADminStatMoniteurVehicule = new javax.swing.JLabel();
        lblLesMoniteursSollicites = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLesMoniteursSollicites = new javax.swing.JTable();
        btnAdminGraphiqueLesVehicules = new javax.swing.JButton();
        lblLesVehiculesSollicites = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLesVehiculesSollicites = new javax.swing.JTable();
        btnAdminGraphiqueVehicule = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUnVehiculeSollicite = new javax.swing.JTable();
        lblUnVehiculeSollicité = new javax.swing.JLabel();

        jScrollPane1.setViewportView(tblUnMoniteurSollicite);

        lblUnMoniteurSollicité.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUnMoniteurSollicité.setText("Le moniteur le plus sollicité");

        lblADminStatMoniteurVehicule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblADminStatMoniteurVehicule.setText("Statistiques des moniteurs et véhicules les plus sollicités ");

        lblLesMoniteursSollicites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLesMoniteursSollicites.setText("Classement des véhicules les plus sollcités");

        jScrollPane2.setViewportView(tblLesMoniteursSollicites);

        btnAdminGraphiqueLesVehicules.setText("Voir le Graphique des moniteurs");
        btnAdminGraphiqueLesVehicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminGraphiqueLesVehiculesMouseClicked(evt);
            }
        });

        lblLesVehiculesSollicites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLesVehiculesSollicites.setText("Les véhicules les plus sollicités");

        jScrollPane4.setViewportView(tblLesVehiculesSollicites);

        btnAdminGraphiqueVehicule.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAdminGraphiqueVehicule.setText("Voir le graphique des véhicules");
        btnAdminGraphiqueVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminGraphiqueVehiculeMouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(tblUnVehiculeSollicite);

        lblUnVehiculeSollicité.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUnVehiculeSollicité.setText("Le véhicule le plus sollicités");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(385, 385, 385)
                .addComponent(lblADminStatMoniteurVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUnVehiculeSollicité)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLesVehiculesSollicites)
                        .addGap(456, 456, 456))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                            .addComponent(lblUnMoniteurSollicité, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLesMoniteursSollicites)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdminGraphiqueLesVehicules, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdminGraphiqueVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblADminStatMoniteurVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLesMoniteursSollicites)
                    .addComponent(lblUnMoniteurSollicité))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUnVehiculeSollicité)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAdminGraphiqueLesVehicules)
                        .addGap(18, 18, 18)
                        .addComponent(lblLesVehiculesSollicites, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdminGraphiqueVehicule)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminGraphiqueLesVehiculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminGraphiqueLesVehiculesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminGraphiqueLesVehiculesMouseClicked

    private void btnAdminGraphiqueVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminGraphiqueVehiculeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminGraphiqueVehiculeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminStatsMoniteurEtVehicule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminStatsMoniteurEtVehicule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminGraphiqueLesVehicules;
    private javax.swing.JButton btnAdminGraphiqueVehicule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblADminStatMoniteurVehicule;
    private javax.swing.JLabel lblLesMoniteursSollicites;
    private javax.swing.JLabel lblLesVehiculesSollicites;
    private javax.swing.JLabel lblUnMoniteurSollicité;
    private javax.swing.JLabel lblUnVehiculeSollicité;
    private javax.swing.JTable tblLesMoniteursSollicites;
    private javax.swing.JTable tblLesVehiculesSollicites;
    private javax.swing.JTable tblUnMoniteurSollicite;
    private javax.swing.JTable tblUnVehiculeSollicite;
    // End of variables declaration//GEN-END:variables
}
