/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vues;

/**
 *
 * @author Rakotomalala Cédric
 */
public class FrmAdminStatistiqueLecons extends javax.swing.JPanel {

    /**
     * Creates new form FrmAdminStatistiqueLecons
     */
    public FrmAdminStatistiqueLecons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitreStatLecon = new javax.swing.JLabel();
        lblAdminStatLeconMoniteur = new javax.swing.JLabel();
        lblAdminStatLeconVehicule = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboStatMoniteur = new javax.swing.JComboBox<>();
        cboStatVehicule = new javax.swing.JComboBox<>();
        cboStatCategorie = new javax.swing.JComboBox<>();
        btnAdminStatLecons = new javax.swing.JButton();
        lblNombreLeconMoniteur = new javax.swing.JLabel();
        lblNombreVehicule = new javax.swing.JLabel();
        lblNombreCategorie = new javax.swing.JLabel();
        tctNbrLeconMoniteur = new javax.swing.JTextField();
        txtNbrLeconVehicule = new javax.swing.JTextField();
        txtNbrLeconCategorie = new javax.swing.JTextField();

        lblTitreStatLecon.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblTitreStatLecon.setText("Le nombre de leçons ");

        lblAdminStatLeconMoniteur.setText("Choisissez un moniteur");

        lblAdminStatLeconVehicule.setText("Choisissez un vehicule");

        jLabel1.setText("Choisissez une catégorie");

        btnAdminStatLecons.setText("Voir le nombre de leçons");

        lblNombreLeconMoniteur.setText("Le nombre de leçons de ce moniteur est de :");

        lblNombreVehicule.setText("Le nombre de leçons de ce véhicule est de :");

        lblNombreCategorie.setText("Le nombre de leçons de cette catégorie est de :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAdminStatLecons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblAdminStatLeconMoniteur)
                                        .addComponent(jLabel1)
                                        .addComponent(lblAdminStatLeconVehicule))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cboStatCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboStatVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboStatMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(lblTitreStatLecon))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreVehicule)
                                .addGap(24, 24, 24)
                                .addComponent(txtNbrLeconVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreCategorie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNbrLeconCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblNombreLeconMoniteur)
                        .addGap(18, 18, 18)
                        .addComponent(tctNbrLeconMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblTitreStatLecon)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminStatLeconMoniteur)
                    .addComponent(cboStatMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminStatLeconVehicule)
                    .addComponent(cboStatVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboStatCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addComponent(btnAdminStatLecons)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreLeconMoniteur)
                    .addComponent(tctNbrLeconMoniteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreVehicule)
                    .addComponent(txtNbrLeconVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNbrLeconCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCategorie))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminStatLecons;
    private javax.swing.JComboBox<String> cboStatCategorie;
    private javax.swing.JComboBox<String> cboStatMoniteur;
    private javax.swing.JComboBox<String> cboStatVehicule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdminStatLeconMoniteur;
    private javax.swing.JLabel lblAdminStatLeconVehicule;
    private javax.swing.JLabel lblNombreCategorie;
    private javax.swing.JLabel lblNombreLeconMoniteur;
    private javax.swing.JLabel lblNombreVehicule;
    private javax.swing.JLabel lblTitreStatLecon;
    private javax.swing.JTextField tctNbrLeconMoniteur;
    private javax.swing.JTextField txtNbrLeconCategorie;
    private javax.swing.JTextField txtNbrLeconVehicule;
    // End of variables declaration//GEN-END:variables
}
