/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vues;

/**
 *
 * @author Rakotomalala Cédric
 */
public class FrmAdminStatistiqueMoniteurEtVehicule extends javax.swing.JPanel {

    /**
     * Creates new form FrmAdminStatistiqueMoniteurEtVehicule
     */
    public FrmAdminStatistiqueMoniteurEtVehicule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblADminStatMoniteurVehicule = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnMoniteurSollicite = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLesMoniteursSollicites = new javax.swing.JTable();
        lblUnMoniteurSollicité = new javax.swing.JLabel();
        lblLesMoniteursSollicites = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblUnVehiculeSollicite = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLesVehiculesSollicites = new javax.swing.JTable();
        lblUnVehiculeSollicité = new javax.swing.JLabel();
        lblLesVehiculesSollicites = new javax.swing.JLabel();
        btnAdminGraphiqueLesVehicules = new javax.swing.JButton();
        btnAdminGraphiqueVehicule = new javax.swing.JButton();

        lblADminStatMoniteurVehicule.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblADminStatMoniteurVehicule.setText("Statistiques des moniteurs et véhicules les plus sollicités ");

        jScrollPane1.setViewportView(tblUnMoniteurSollicite);

        jScrollPane2.setViewportView(tblLesMoniteursSollicites);

        lblUnMoniteurSollicité.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUnMoniteurSollicité.setText("Le moniteur le plus sollicité");

        lblLesMoniteursSollicites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLesMoniteursSollicites.setText("Classement des véhicules les plus sollcités");

        jScrollPane3.setViewportView(tblUnVehiculeSollicite);

        jScrollPane4.setViewportView(tblLesVehiculesSollicites);

        lblUnVehiculeSollicité.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblUnVehiculeSollicité.setText("Le véhicule le plus sollicités");

        lblLesVehiculesSollicites.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblLesVehiculesSollicites.setText("Les véhicules les plus sollicités");

        btnAdminGraphiqueLesVehicules.setText("Voir le Graphique des moniteurs");
        btnAdminGraphiqueLesVehicules.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminGraphiqueLesVehiculesMouseClicked(evt);
            }
        });

        btnAdminGraphiqueVehicule.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAdminGraphiqueVehicule.setText("Voir le graphique des véhicules");
        btnAdminGraphiqueVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdminGraphiqueVehiculeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(lblADminStatMoniteurVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                .addGap(335, 335, 335))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUnMoniteurSollicité)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLesMoniteursSollicites)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblUnVehiculeSollicité)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLesVehiculesSollicites)
                .addGap(403, 403, 403))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdminGraphiqueVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdminGraphiqueLesVehicules, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblADminStatMoniteurVehicule, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnMoniteurSollicité)
                    .addComponent(lblLesMoniteursSollicites))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblUnVehiculeSollicité))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdminGraphiqueLesVehicules)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLesVehiculesSollicites, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdminGraphiqueVehicule)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminGraphiqueVehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminGraphiqueVehiculeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminGraphiqueVehiculeMouseClicked

    private void btnAdminGraphiqueLesVehiculesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminGraphiqueLesVehiculesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminGraphiqueLesVehiculesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminGraphiqueLesVehicules;
    private javax.swing.JButton btnAdminGraphiqueVehicule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblADminStatMoniteurVehicule;
    private javax.swing.JLabel lblLesMoniteursSollicites;
    private javax.swing.JLabel lblLesVehiculesSollicites;
    private javax.swing.JLabel lblUnMoniteurSollicité;
    private javax.swing.JLabel lblUnVehiculeSollicité;
    private javax.swing.JTable tblLesMoniteursSollicites;
    private javax.swing.JTable tblLesVehiculesSollicites;
    private javax.swing.JTable tblUnMoniteurSollicite;
    private javax.swing.JTable tblUnVehiculeSollicite;
    // End of variables declaration//GEN-END:variables
}
